language: php

php: 
  - 7.1
  - 7.2

before_script:
  - composer install --no-interaction
  - cp vendor/laravel/laravel/.env.example .env
  - touch database/database.sqlite

script:
  - vendor/bin/phpunit